#!/bin/bash
git clone https://github.com/kdrag0n/aarch64-elf-gcc gcc-64 &> /dev/null
git clone https://github.com/ProtoChuz/linaro-mirror -b 4.9-32 gcc-32 &> /dev/null
git clone https://github.com/ProtoChuz/AnyKernel3 &> /dev/null

make clean distclean mrproper &> /dev/null
clear
clear
CROSS_COMPILE=$(pwd)/gcc-64/bin/aarch64-elf-
CROSS_COMPILE_ARM32=$(pwd)/gcc-32/bin/arm-linux-gnueabi-
export ARCH=arm64
export KBUILD_BUILD_USER=Akmal
export KBUILD_BUILD_HOST=KekSerbor
export CROSS_COMPILE
export CROSS_COMPILE_ARM32

curl -F chat_id="665641885" -F parse_mode="HTML" -F text="Building <b>Everest Kernel</b>
Last Commit : <code>$(git log --oneline --decorate --color --pretty=%s --first-parent -1)</code>
Build Started on : <code>$(date)</code>" https://api.telegram.org/bot698235574:AAGpwfSHtl669jA2JP2nhycee5ZdyM0SmD4/sendMessage &> /dev/null

rm -rf output
make  -s -C "$(pwd)" O=output santoni_defconfig
make -j8 -s -C "$(pwd)" O=output

if [ ! -f output/arch/arm64/boot/Image.gz ]; then
    curl -F chat_id="-1001324692867" -F document=@"${CTIME}-Log.txt" https://api.telegram.org/bot698235574:AAGpwfSHtl669jA2JP2nhycee5ZdyM0SmD4/sendDocument &> /dev/null
    curl -F chat_id="665641885" -F text="Build throw an error(s)" https://api.telegram.org/bot698235574:AAGpwfSHtl669jA2JP2nhycee5ZdyM0SmD4/sendMessage &> /dev/null
else
CTIME=$(date +'%m%d-%H%M')
cp output/arch/arm64/boot/Image.gz-dtb AnyKernel3/zImage
cd AnyKernel3 || exit
rm -rf *.zip
zip -r9 "zEAS-${CTIME}.zip" * -x README.md &> /dev/null
curl -F chat_id="665641885" -F document=@"zEAS-${CTIME}.zip" https://api.telegram.org/bot698235574:AAGpwfSHtl669jA2JP2nhycee5ZdyM0SmD4/sendDocument &> /dev/null
fi
